export const collectionsActionTypes = {
  GET_COLLECTIONS_START: "GET_COLLECTIONS_START",
  GET_COLLECTIONS_SUCCESS: "GET_COLLECTIONS_SUCCESS",
  GET_COLLECTIONS_FAILURE: "GET_COLLECTIONS_FAILURE",
  COLLECTIONS_DELETE_GIF_START: "COLLECTIONS_DELETE_GIF_START",
  COLLECTIONS_DELETE_GIF_FAILURE: "COLLECTIONS_DELETE_GIF_FAILURE",
  COLLECTIONS_EDIT_NAME_START: "COLLECTIONS_EDIT_NAME_START",
  COLLECTIONS_EDIT_NAME_SUCCESS: "COLLECTIONS_EDIT_NAME_SUCCESS",
  COLLECTIONS_EDIT_NAME_FAILURE: "COLLECTIONS_EDIT_NAME_FAILURE",
  COLLECTIONS_EDIT_IS_SHARED_START: "COLLECTIONS_EDIT_IS_SHARED_START",
  COLLECTIONS_EDIT_IS_SHARED_FAILURE: "COLLECTIONS_EDIT_IS_SHARED_FAILURE",
  COLLECTIONS_ADD_GIF_TO_COLLECTION_START:
    "COLLECTIONS_ADD_GIF_TO_COLLECTION_START",
  COLLECTIONS_ADD_GIF_TO_COLLECTION_SUCCESS:
    "COLLECTIONS_ADD_GIF_TO_COLLECTION_SUCCESS",
  COLLECTIONS_ADD_GIF_TO_COLLECTION_FAILURE:
    "COLLECTIONS_ADD_GIF_TO_COLLECTION_FAILURE",
  COLLECTIONS_DELETE_START: "COLLECTIONS_DELETE_START",
  COLLECTIONS_DELETE_SUCCESS: "COLLECTIONS_DELETE_SUCCESS",
  COLLECTIONS_DELETE_FAILURE: "COLLECTIONS_DELETE_FAILURE",
  COLLECTIONS_ADD_NEW_COLLECTION_START: "COLLECTIONS_ADD_NEW_COLLECTION_START",
  COLLECTIONS_ADD_NEW_COLLECTION_SUCCESS:
    "COLLECTIONS_ADD_NEW_COLLECTION_SUCCESS",
  COLLECTIONS_ADD_NEW_COLLECTION_FAILURE:
    "COLLECTIONS_ADD_NEW_COLLECTION_FAILURE",
};
